[package]
name = "dmens"
version = "0.1.0"
#published-at = "0xe7fb386dc1b6126b3bb3d615bd26e14fde399a4cc5663758011804c1283ad228"

[dependencies]
#Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "testnet" }
Sui = { local = "../sui/crates/sui-framework/packages/sui-framework" }

[addresses]
dmens =  "0x0"
